export { default as mango } from './mango.png'
export { default as pera } from './pera.png'
export { default as rojo } from './rojo.png'
export { default as zanahoria } from './zanahoria.png'

export { default as personTestimonial } from './person-testimonial.jpg'
export { default as personTestimonial1 } from './person-testimonial1.jpg'
export { default as personTestimonial2 } from './person-testimonial2.jpg'
export { default as personTestimonial3 } from './person-testimonial3.jpg'
export { default as personTestimonial4 } from './person-testimonial4.jpg'
export { default as personTestimonial5 } from './person-testimonial5.jpg'
export { default as personTestimonial6 } from './person-testimonial6.jpg'
export { default as personTestimonial7 } from './person-testimonial7.jpg'
export { default as personTestimonial8 } from './person-testimonial8.jpg'
export { default as personTestimonial9 } from './person-testimonial9.jpg'
export { default as personTestimonial10 } from './person-testimonial10.jpg'
